---
- hosts: all
  vars_files:
    - ../vault.yml

  tasks:
    - name: Add superuser with a bash shell
      user:
        name: '{{ item }}'
        shell: /bin/bash
        groups: wheel
        append: yes
        password: "{{ ansible_become_password | password_hash('sha512') }}"
        # generate_ssh_key: true
        # ssh_key_type: ssh-ed25519
      with_items: '{{ user }}'
      when:
        - item == "ansible"
    - name: Add user with a bash shell
      user:
        name: '{{ item }}'
        shell: /bin/bash
        groups: wheel
        append: yes
        password: "{{ ansible_become_password | password_hash('sha512') }}"
        # generate_ssh_key: true
        # ssh_key_type: ssh-ed25519
      with_items: '{{ user }}'
      when:
        - item != "ansible"
    - name: Set authorized keys for ansible controller
      become: true
      authorized_key:
        user: '{{ item }}'
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ssh_ed25519_' + item + '_' + inventory_hostname + '.pub') }}"
      with_items: '{{ users }}'
