---
- hosts: all
  become: true
  vars_files:
    - ../vault.yml

  pre_tasks:
    - name: Create nginx ssl directory
      file:
        path: /etc/ssl/nginx
        state: directory

  tasks:
    - name: Install pip3
      become: true
      package:
        name: "python3-pip"
        state: present
    - name: Upgrade pip
      pip:
        name: pip
        extra_args: --upgrade
    - name: Install cryptography python package
      pip:
        name: cryptography
    - name: Generate an OpenSSL private key
      openssl_privatekey:
        path: "/etc/ssl/nginx/{{ item | replace('.', '_') }}_privkey.pem"
        size: "{{ key_size }}"
        type: "{{ key_type }}"
        #cipher: auto
        #passphrase: "{{ passphrase }}"
        backup: yes
      with_items:
        - "{{ domains }}"
    - name: Generate an OpenSSL Certificate Signing Request with Subject information
      openssl_csr:
        path: "/etc/ssl/nginx/{{ item | replace('.', '_') }}.csr"
        privatekey_path: "/etc/ssl/nginx/{{ item | replace('.', '_') }}_privkey.pem"
        country_name: "{{ country_name }}"
        organization_name: "{{ organization_name }}"
        email_address: "{{ email_address }}"
        common_name: "{{ item }}"
        #privatekey_passphrase: "{{ passphrase }}"
      with_items:
        - "{{ domains }}"
    - name: Pull OpenSSL Certificate Signing Request
      fetch: 
        src: "/etc/ssl/nginx/{{ item | replace('.', '_') }}.csr"
        dest: "~/ssl/{{ item | replace('.', '_') }}.csr"
        flat: true
      with_items:
        - "{{ domains }}"
    - name: Sign certificate with our CA
      delegate_to: localhost
      become: false
      openssl_certificate:
        path: ~/ssl/{{ item | replace('.', '_') }}_cert.pem
        csr_path: ~/ssl/{{ item | replace('.', '_') }}.csr
        provider: ownca
        ownca_path: ~/ssl/ca_cert.pem
        ownca_privatekey_path: ~/ssl/ca_privkey.pem
        ownca_privatekey_passphrase: "{{ ca_passphrase }}"
        ownca_not_after: +365d  # valid for one year
        ownca_not_before: "-1d"  # valid since yesterday
      with_items:
        - "{{ domains }}"
    - name: Push certificate
      copy:
        src: "~/ssl/{{ item | replace('.', '_') }}_cert.pem"
        dest: "/etc/ssl/nginx/{{ item | replace('.', '_') }}_cert.pem"
      with_items:
        - "{{ domains }}"
    - name: Push CA
      copy: 
        src: "~/ssl/ca_cert.pem"
        dest: "/etc/ssl/nginx/ca_cert.pem"